# Generated by Django 4.2.29 on 2026-03-17 12:09

from django.db import migrations, models
import uuid
import vault.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to=vault.models.upload_to_encrypted)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
            ],
        ),
    ]
